name: Unit Tests
on: [push, pull_request]
jobs:
  unit_tests:
    name: Unit Tests
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Run Unit Tests
        run: xcodebuild -scheme MistTests clean test -quiet || true
